// APPA Art Fest 2027 · every word in the app, and what every control does.
// Controls (see src/app/app.js):
//   { type: 'button', label, actions: [...] , primary }
//   { type: 'toggle', label, labelOn, channel, arg, on: value, off: value, also: [{ channel, arg, on, off }] }
//   { type: 'slider', label, channel, min, max, step, readout: v => text }
//   { type: 'choice', label, channel, options: [{ label, value, text, actions }] }
// Actions: { set: channel, arg, value } · { pulse: channel, arg, dur } · { go: 'area:<id>' | 'spot:<key>' | 'overview' } · { reveal: areaId } · { say: text }

const WEEKS = [
  { label: 'Roots & Raga', dates: 'Week 1 · 25 Jan to 1 Feb', text: 'Classical, Maharashtra culture, fusion, desi cool and global artists. The festival opens on 25 January, the eve of Republic Day.', value: 0 },
  { label: 'Keeping it Real', dates: 'Week 2 · 2 to 8 Feb', text: 'Hip-hop, rap, spoken word, poetry, rock and youth culture.', value: 1 },
  { label: 'Tech, Electronica & AI', dates: 'Week 3 · 9 to 15 Feb', text: 'Electronic music, digital art, AI, immersive installations and tech-driven creativity.', value: 2 },
  { label: 'All forms, together', dates: 'Weeks 4 and 5 · 16 to 25 Feb', text: 'A grand culmination of everything: music, art, workshops, community creations and special collaborations.', value: 3 },
  { label: 'The Encore · VVIP/VIP only', dates: 'Bonus · 26 to 28 Feb', text: 'Three extra days after the festival closes, open only to VVIP and VIP guests: special access and personal meet-ups with resident artists.', value: 4, restricted: true }
];
const weekOptions = WEEKS.map(w => ({ label: w.label, value: w.value, text: `${w.dates}. ${w.text}`, actions: [{ set: 'dronesOn', value: w.value === 2 ? 1 : 0 }] }));
const showToggle = (area, label, labelOn) => ({ type: 'toggle', label, labelOn, channel: 'stageOn', arg: area, on: 1, off: 0, also: [{ channel: 'crowd', arg: area, on: 1, off: 0.45 }] });
const dusk = { type: 'button', label: 'Let the evening come', actions: [{ set: 'timeOfDay', value: 0.86 }] };
// a venue's own site, opened in a new tab so the festival app keeps running behind it.
// venues with no official website of their own get a plain search link instead of a made-up address.
const site = (label, url) => ({ label, url });
const search = q => `https://www.google.com/search?q=${encodeURIComponent(q)}`;

// ticket tiers for the ticket counter (subject to change as the plan firms up)
const TICKETS = {
  title: 'Tickets & stays', eyebrow: 'The ticket counter',
  intro: 'Everything to come to APPA Art Fest 2027, from a single day to the whole month. Prices are early plans and may change.',
  tiers: [
    { name: 'Day pass', price: '₹2,000', unit: 'per person, per day', blurb: 'Entry to the festival for one day: every venue, every open show.', bullets: ['Access to all open venues for the day', 'Exhibitions, art walks and open workshops', 'No stay included'] },
    { name: 'Stay + festival, for 2', price: '₹10,000', unit: 'per night (a 24-hour stay)', blurb: 'A night’s stay for two, with festival tickets for two included.', bullets: ['One night’s stay for 2 guests at a partner venue', 'Festival tickets for 2 people, for that day', 'Cycle or e-bike pickup at check-in', 'Kids under 10: free entry with a paying adult'] },
    { name: 'VIP · 1 week', price: 'On request', unit: 'a 7-day booking', blurb: 'A week at the festival with full access to every show and experience.', bullets: ['All shows and experiences for 7 days', 'Priority entry at every venue', 'A stay for the week (partner venue, subject to availability)'] },
    { name: 'VVIP · 30 days', price: 'On request', unit: 'the full month, stay + experience', blurb: 'The whole festival, start to finish: full access plus a few things nobody else gets.', bullets: ['All access, all 30 days, every venue', 'A few special-access moments across the month', 'Personal meet-ups with resident artists', 'Stay for the full run (partner venue, subject to availability)'] }
  ],
  note: 'Kids under 10 always enter free, on every ticket type. Exact stay partner is assigned at booking, based on availability.',
  qr: { image: './assets/tickets_qr.png', caption: 'Scan to pay by UPI', payee: 'Karthikeyan Ramachandran', upi: 'xtrathindesign@okicici' },
  contact: 'To book, scan the QR to pay, then share the payment screenshot along with your dates and headcount on WhatsApp.'
};


// Join the festival: volunteer, partner, sponsor. Early draft wording, all of it is meant to be edited.
const JOIN = {
  volunteer: { button: 'Be a volunteer', eyebrow: 'Be a volunteer', title: 'Help build a season',
    intro: 'A month-long festival runs on people. Volunteers are the friendly faces at every venue: they greet guests, help artists set up, keep the cycle stands moving and make the whole lake feel like one big welcome.',
    blocks: [
      { h: 'Where you could help', bullets: ['Guest welcome and wayfinding at check-in and at every venue', 'The cycle and e-bike desk: fitting, handing out and checking bikes', 'Artist hosts: looking after resident artists and their materials', 'Workshop assistants: setting up, guiding and clearing', 'Stage and show crew: lights, sound, seating, backstage', 'The green team: waste, water and keeping the lake clean', 'Kids’ corner and family help', 'Photo, video and reels for the festival’s own channels'] },
      { h: 'What you get', bullets: ['Meals on shift and a place to stay', 'Free festival access on your days off, including workshops', 'A chance to meet and talk with the artists', 'A volunteer certificate and a reference on request', 'Being part of the first APPA season'] },
      { h: 'How it works', bullets: ['Open to everyone 18 and over; people from the villages around the lake are especially welcome', 'Shifts of about five hours; a minimum of three days', 'A short orientation before the festival opens on 25 January'] }
    ],
    contact: 'Tell us your name, the days you can come and where you would like to help. We will reply with a shift plan.',
    cta: { label: 'Volunteer sign-up: contact details coming soon' } },
  partner: { button: 'Be a partner', eyebrow: 'Be a partner', title: 'Make Kamshet a season',
    intro: 'APPA is a festival of festivals, and it belongs to the whole lake. We are inviting stays, farms, theatres, collectives, schools, local businesses and civic bodies to become partners and grow a February season for Kamshet that people plan their year around.',
    blocks: [
      { h: 'Who we would love to work with', bullets: ['Stays, farms and retreats around the lake (venue partners)', 'Theatres, collectives, studios and schools that want to curate their own festival within ours', 'Local makers, food producers and village communities', 'Civic and government partners: district administration, police, tourism, forest and local bodies', 'Mobility partners: cycles, e-bikes and electric two-wheelers', 'Media and culture partners'] },
      { h: 'What we ask of venue partners', bullets: ['Open and common spaces for performances, exhibitions and workshops', 'About one room in five for a resident artist, whose work in progress your guests get to watch', 'Your own festival or programme inside APPA, if you would like one'] },
      { h: 'What partners receive', bullets: ['A full month of bookings, instead of the usual handful of busy days', 'A share of ticket income from paid events at your venue', 'Your name and logo in festival media, the app and the press', 'A place on the map, the tour and the itinerary every guest carries', 'Early-partner status as the festival grows year after year'] },
      { h: 'For government and civic partners', bullets: ['A public inauguration on 25 January, the eve of Republic Day', 'Recognition as a founding supporter in all press and communication', 'A safe, well-run and well-planned event, built together from day one'] }
    ],
    contact: 'Write to us about the space, service or programme you would like to bring, and we will set up a conversation.',
    cta: { label: 'Partner enquiries: contact details coming soon' } },
  sponsor: { button: 'Be a sponsor', eyebrow: 'Be a sponsor', title: 'Back the season',
    intro: 'APPA Art Fest 2027 is dedicated to the late artist K. N. Ramachandran: a month of art, people and nature across a whole lake, with cycles instead of cars and a new artist at work in every corner. Sponsors make it possible, and we make sure they are seen.',
    tiers: [
      { name: 'Title sponsor', price: '₹60 lakh and above', unit: 'one only · indicative', blurb: 'The festival carries your name for the month.', bullets: ['“APPA Art Fest 2027 presented by …” on everything', 'Main-stage and inauguration branding on 25 January', 'Your name in the app, the tour and the press release', 'A private evening and artist meet-up for your guests', 'A film and reels package across the month'] },
      { name: 'Week sponsor', price: '₹15 to 20 lakh', unit: 'four available, one per week · indicative', blurb: 'Own a week and its theme: Roots & Raga, Keeping it Real, Tech & AI, All Forms Together.', bullets: ['Your name on that week’s programme and stages', 'Weekend headline slot branding', 'Social and reel features through the week'] },
      { name: 'Venue sponsor', price: '₹4 to 8 lakh', unit: 'one per venue · indicative', blurb: 'Be the presenting sponsor of one of the venues.', bullets: ['Your name beside the venue’s on the map and in the app', 'Signage at the venue', 'A curated moment with the venue’s resident artists'] },
      { name: 'Event or stage sponsor', price: '₹1.5 to 3 lakh', unit: 'many available · indicative', blurb: 'Back one show, workshop, screening or stage.', bullets: ['Your name on the show’s billing and stage', 'Mentions in social posts and reels for the event'] },
      { name: 'Artist sponsor', price: '₹50,000 to ₹1 lakh', unit: 'many available · indicative', blurb: 'Support one resident artist: materials, stay and travel.', bullets: ['Your name beside the artist’s work and residency', 'A studio visit and a piece for your collection or office'] },
      { name: 'In-kind and barter', price: 'Value-matched', unit: 'cycles, e-bikes, food, sound, print, travel and more', blurb: 'Pay in product or service instead of cash.', bullets: ['Logo on signage, the map and the app', 'Reels and shout-outs matched to the value you bring', 'Cycle and e-bike partners: a presence at every check-in'] }
    ],
    note: 'Figures are early and open to discussion. Every sponsor is named in the app, on the signage and in the reels.',
    contact: 'Tell us which tier interests you and we will send the full sponsorship proposal.',
    cta: { label: 'Sponsorship enquiries: contact details coming soon' } }
};

export const COPY = {
  join: JOIN,
  brand: 'APPA', title: 'APPA Art Fest 2027',
  tickets: TICKETS,
  intro: { eyebrow: '25 Jan to 25 Feb 2027', h1: 'APPA Art Fest 2027', tag: 'When minds co-create',
    text: 'A festival of festivals: a month of art, people, nature and a better tomorrow, where every venue curates its own festival. One lake, many venues, a living ecosystem. Drag to look around, scroll or pinch to zoom, and tap any venue to see what happens there.',
    enter: 'Enter the festival', loading: 'Loading the festival…' },
  tourLabel: 'Guided tour', tourStop: 'Stop the tour',
  overview: { eyebrow: 'The festival at a glance', h2: 'One lake. Many venues. A living ecosystem.', text: 'Welcome to the festival of festivals. Each venue runs its own festival inside one big fest. Wake up to fine arts, installations, films, theatre, spoken word, fashion, forums, workshops, digital interactive installations, music and nature. Curate your experiences to create your memories.',
    quote: { text: 'Art procreates when minds co\u2011create.', by: 'Appa' },
    controls: [
      { type: 'choice', label: '4 weeks, plus the Encore', channel: 'week', options: weekOptions },
      { type: 'slider', label: 'Time of day', channel: 'timeOfDay', min: 0.1, max: 1, step: 0.01, readout: v => (v < 0.3 ? 'Morning' : v < 0.45 ? 'Afternoon' : v < 0.62 ? 'Golden hour' : v < 0.8 ? 'Dusk' : 'Night') },
      { type: 'button', label: 'Light the lotus on the lake', actions: [{ pulse: 'lotusGlow', dur: 16 }, { go: 'spot:lotus' }] },
      { type: 'button', label: 'Find Hidden APPA', actions: [{ reveal: 'hidden' }, { go: 'area:hidden' }] }
    ],
    journey: ['Park your car at check-in', 'Pick your ride: cycles and e-bikes', 'Get your APPA passport and itinerary', 'Explore every venue: performances, exhibitions, workshops, flea, food and more', 'Stay, unwind, connect with nature', 'Be part of a bigger story'] },
  weeks: WEEKS,
  areas: {
    raiker: { n: 3, name: 'Secret Farm', tagline: 'The biggest gatherings, with parking on site',
      website: site('Find it on Google ↗', search('Raiker Farms Kamshet')),
      offerings: [['Big-scale music performances', 'raiker-stage'], ['Public forums, town halls and debates', 'raiker-stage'], ['Theatre performances and award functions', 'raiker-stage'], ['Different acoustic artists', 'raiker-fire'], ['Multiple art installations', 'raiker-head'], ['Multiple interactive installations', 'raiker-crystals'], ['Four exhibitions', 'raiker-gallery'], ['One mega K. N. Ramachandran exhibition', 'raiker-mega'], ['Farm visits, farm treks and permaculture', 'raiker-farm'], ['Farm to table under the fruit trees', 'raiker-table'], 'On-site parking for the big crowds', 'Flower polyhouses, buffalo stables, lotus pond: the working farm stays part of the show', 'Facing the sunset: sound healing and meditation circles at dusk'] },
    lefarm: { n: 1, name: 'Le Farm', tagline: 'Big events and open debate',
      website: site('lefarm.in ↗', 'https://lefarm.in'),
      offerings: [['Big-scale concerts and music performances', 'lefarm-stage'], ['Political forums, debates and rallies (all voices, curated)', 'lefarm-stage'], ['Morning yoga, meditation and healing sessions', 'lefarm-yoga'], ['Wine and cheese sessions, and fine dine', 'lefarm-tent2'], ['A beer fest under the big top', 'lefarm-beer'], ['Farm visits, permaculture treks and temple visits', 'lefarm-shrine'], ['About 12 resident artists: painters and sculptors', 'lefarm-house'], ['About 5 exhibits: an antique exhibit and the K. N. Ramachandran sketches', 'lefarm-exhibits'], ['An AI futuristic interactive exhibit', 'lefarm-ring'], ['Woodcut workshop', 'lefarm-woodcut'], ['On-site parking for the big crowds', 'lefarm-stage'], ['Facing the sunrise: yoga and meditation on the lawns at first light', 'lefarm-yoga']] },
    shambhala: { n: 2, name: 'Shambhala by the Lake', tagline: 'Intimate music by the water',
      website: site('shambalabythelake.com ↗', 'https://shambalabythelake.com'),
      offerings: [['One art exhibition', 'shambhala-exhibit'], ['3 resident artists: painters, a rock-balancing artist, and acoustic musicians and singers', 'shambhala-cottage'], ['Rock balancing by the water', 'shambhala-rocks'], ['Tricks and a carpentry workshop', 'shambhala-workshop'], ['Intimate music on the lakeside stage', 'shambhala-stage'], ['Jetty sessions, sunrise yoga and lakeside reflections', 'shambhala-stage'], 'Paragliding base for the brave', 'Homely food and weekend barbecue'] },
    purrom: { n: 5, name: 'Purrom', tagline: 'Horror film festival in a healing retreat',
      website: site('purrom.com ↗', 'https://purrom.com'),
      offerings: [['Horror film festival, curated by Purrom', 'purrom-screen'], ['Late-night screenings under the Sahyadri sky', 'purrom-screen'], ['2 to 3 resident artists and painters', 'purrom-domes'], ['One exhibition, in the clay huts', 'purrom-domes'], ['One acoustic act, and music performances', 'purrom-acoustic'], ['One hands-on workshop', 'purrom-workshop'], ['Sunrise meditation, yoga and sound healing', 'purrom-yoga'], ['Stays in the solo domes, the Glass House and the Chickoo house', 'purrom-glass'], ['Flea and local food', 'purrom-market']] },
    company: { n: 6, name: 'The Company Theatre', tagline: 'Their own theatre festival',
      website: site('thecompanytheatre.net ↗', 'https://thecompanytheatre.net'),
      offerings: [['Theatre performances: the Company Theatre’s own festival', 'company-theatre'], ['Theatre workshops', 'company-pavilion'], ['6 resident artists: painters and sculptors', 'company-studio'], ['2 installations', 'company-ring'], ['1 interactive installation', 'company-interactive'], ['An exhibit of K. N. Ramachandran’s work', 'company-studio'], ['Film screenings and talks', 'company-screen'], ['Facing the sunset: meditation at dusk', 'company-sunset']] },
    theeya: { n: 7, name: 'Theeya Creation Village', tagline: 'Voice, craft and community',
      website: site('Search Theeya Creation Village, Kamshet ↗', search('Theeya The Creation Village Kamshet')),
      offerings: [['Singers and song performances: the vocal stage', 'theeya-stage'], ['Theatre', 'theeya-theatre'], ['Fine dine', 'theeya-deck'], ['About 4 resident artists', 'theeya-house'], ['About 3 installations, made on site', 'theeya-installations'], ['Music performances and sing-along evenings by the village fire', 'theeya-fire'], ['Sunrise meditation, yoga and sound healing', 'theeya-yoga'], ['Workshops with local makers', 'theeya-pavilion'], 'Sustainable living and food'] },
    calmshet: { n: 4, name: 'Calmshet', tagline: 'The past two years, fashion and art',
      website: site('calmshet.com ↗', 'https://calmshet.com'),
      offerings: [['Opening night and major performances', 'calmshet-stage'], ['Art exhibition: paintings by the late K. N. Ramachandran', 'calmshet-archive'], ['Exhibit: artists from around India’s independence era', 'calmshet-archive'], ['Antique prints and lithographs', 'calmshet-prints'], ['Comics corner with an interactive, immersive AI exhibit', 'calmshet-ai'], ['Interactive installations and immersive experiences', 'calmshet-ai'], ['Short films', 'calmshet-film'], ['10 resident painters working on the verandas', 'calmshet-house'], ['A sculptor in residence, and sculpture on the lawn', 'calmshet-sculpture'], ['Pottery workshop', 'calmshet-pottery'], ['Acoustic sets, sunset sets and sunset evening views', 'calmshet-stage'], ['The archive: every event of the last two years and their formats', 'calmshet-archive'], ['Fashion segment with a runway', 'calmshet-runway'], ['Facing the sunset: sound healing and meditation at dusk', 'calmshet-sunset']] },
    checkin: { name: 'Check-in & Festival Square', tagline: 'Where the journey starts, and where everyone gathers', offerings: ['Park your car and walk in under the APPA arch', 'Pick up a cycle or an e-bike', 'Your APPA passport and itinerary', 'The fire pit: sing-alongs and stories every night', 'A stage for open mics, local bands and the day’s surprises', 'Flea, food and craft stalls on the shore', 'Boats out to the Island Cinema'] },
    island: { name: 'Island Cinema', tagline: 'Films on an island in the middle of the lake', offerings: ['Open-air screenings every evening, under string lights', 'Reached by boat from the jetties', 'Short films, documentaries and the horror festival’s late shows', 'Blankets and benches: bring a friend'] },
    camp: { name: 'Stay & Unwind', tagline: 'More than a festival, a place to belong', offerings: ['Camping and eco-stays', 'Homestays and local stays', 'Quiet zones, wellness and retreats', 'Stay for a night or the whole month'] },
    hidden: { name: 'Hidden APPA', tagline: 'Offbeat acts in fields, forests and villages', offerings: ['Pop-up performances', 'Reached by cycle or on foot', 'Ask at any venue where tonight’s act is'] }
  },
  spots: {
    'raiker-stage': { area: 'raiker', pos: [7, 70, 3], programme: ['Big-scale music performances', 'Public forums, town halls and debates', 'Theatre performances', 'Award functions'], title: 'The forum stage', text: 'The largest stage on the farm, with parking behind and hills beyond: public forums, town halls and big performances. The crowd fills in when it starts.', controls: [showToggle('raiker', 'Open the forum', 'Close the forum'), dusk] },
    'raiker-head': { area: 'raiker', pos: [24, 73, 4], programme: ['Multiple art installations across the farm', 'Come back at dusk: the eyes light up'], title: 'The head in the field', text: 'A giant, calm face in brass with a slow ring around it. Come back at dusk: its eyes light up.', controls: [dusk] },
    'raiker-table': { area: 'raiker', pos: [24, 57, 2], programme: ['Farm-to-table meals', 'Long tables under the fruit trees'], title: 'Farm to table', text: 'Long tables under a roof, food from the fields around you.' },
    'raiker-farm': { area: 'raiker', pos: [25, 64, 2], programme: ['Farm visits', 'Farm treks', 'Permaculture walks'], title: 'The working farm', text: 'Flower polyhouses and buffalo stables stay part of the visit: walk the farm between sessions.' },
    'raiker-house': { area: 'raiker', pos: [15, 60, 4], programme: ['The mega K. N. Ramachandran exhibition', 'Resident artists working on the verandas'], title: 'The farmhouse', text: 'The cream farmhouse with its twin red gables and the double staircase curving up to the balcony. Resident artists work on the verandas.', controls: [dusk] },
    'lefarm-stage': { area: 'lefarm', pos: [64.5, 111, 3], programme: ['Big-scale concerts', 'Music performances', 'Forums, debates and rallies'], title: 'The open-debate stage', text: 'Political forums, debates and rallies, curated for every voice. Parking is on site.', controls: [showToggle('lefarm', 'Open the forum', 'Close the forum'), dusk] },
    'lefarm-tops': { area: 'lefarm', pos: [52, 114, 5], programme: ['Beer fest', 'Big-scale concerts and music performances'], title: 'The big tops', text: 'Two striped tents for music and performance, lit from inside after dark.', controls: [dusk] },
    'lefarm-house': { area: 'lefarm', pos: [57, 102, 4], programme: ['About 12 resident artists: painters and sculptors', 'About 5 exhibits: the antique exhibit, the K. N. Ramachandran sketches, and more across the grounds'], title: 'The main house', text: 'A modern two-storey house with flat roofs, big glass windows, a rounded veranda and a carport: the artists’ green room.' },
    'lefarm-ring': { area: 'lefarm', pos: [71, 107.5, 3], zoom: 1.6, programme: ['An AI futuristic interactive exhibit', 'A major outdoor installation'], title: 'The red sculpture', text: 'A tall faceted sculpture on the lawn, a major outdoor installation. It glows after dark.', controls: [dusk] },
    'shambhala-stage': { area: 'shambhala', pos: [44, 82, 2.5], programme: ['Acoustic musicians and singers', 'Intimate sets by the water', 'Sunrise yoga on the jetty'], title: 'The lakeside stage', text: 'Small, close, by the water: intimate sets for a few dozen people.', controls: [showToggle('shambhala', 'Start a lakeside set', 'End the set')] },
    'shambhala-house': { area: 'shambhala', pos: [31, 84, 3], programme: ['One art exhibition', 'Long meals and music'], title: 'The pavilion', text: 'A big open pavilion with a red tiled roof, up the stone steps: long meals, music and artists in residence, right by the water.', controls: [dusk] },
    'purrom-screen': { area: 'purrom', pos: [47, 23, 3], programme: ['Horror film festival', 'Late-night screenings under the Sahyadri sky'], title: 'The horror film festival', text: 'Screenings after dark in the open air, beside a retreat that heals by day.', controls: [showToggle('horror', 'Start a screening', 'End the screening'), { type: 'button', label: 'Make it night', actions: [{ set: 'timeOfDay', value: 0.95 }] }] },
    'purrom-domes': { area: 'purrom', pos: [47, 13, 3], programme: ['2 to 3 resident artists and painters', 'One exhibition in the huts'], title: 'The clay huts and the Glass House', text: 'Square clay huts under red pyramid roofs, clay pots, and the Glass House dome with valley views, glowing softly at night.', controls: [dusk] },
    'purrom-market': { area: 'purrom', pos: [40, 28, 2], programme: ['Flea and local food', 'Handmade, sustainable products'], title: 'The flea and food', text: 'Handmade, sustainable, local products and food.' },
    'company-theatre': { area: 'company', pos: [73, 13, 4], programme: ['Theatre performances', 'The Company Theatre’s own festival'], title: 'The theatre house', text: 'The white house with the red roof and the railed veranda, home of The Company Theatre and its festival. Curtain up on new work.', controls: [showToggle('company', 'Curtain up', 'Curtain down')] },
    'company-screen': { area: 'company', pos: [69, 22, 3], programme: ['Film screenings', 'Talks under the stars'], title: 'The open-air screen', text: 'Film screenings and talks under the stars, on benches in the grass.', controls: [{ ...showToggle('company', 'Start the screening', 'End the screening') }, dusk] },
    'theeya-stage': { area: 'theeya', pos: [119.5, 69, 2.5], programme: ['Singers and song performances', 'Choirs and voice workshops'], title: 'The vocal stage', text: 'Solo voices, choirs and voice workshops under the trees, led by the village’s own singer.', controls: [showToggle('theeya', 'Start the singing', 'End the singing'), dusk] },
    'theeya-pavilion': { area: 'theeya', pos: [121, 60, 3], programme: ['Workshops with local makers', 'Sunrise meditation, yoga and sound healing'], title: 'The workshop pavilion', text: 'Hands-on workshops with local makers: clay, weaving, natural dyes, cooking.' },
    'theeya-deck': { area: 'theeya', pos: [107, 70, 2], programme: ['Fine dine', 'Long meals and quiet mornings'], title: 'The pergola deck', text: 'Long tables under the timber pergola beside the red house, wrapped in bougainvillea. Meals, conversations and quiet mornings.', controls: [dusk] },
    'theeya-fire': { area: 'theeya', pos: [113.5, 66.5, 1.5], programme: ['Sing-along evenings', 'Music performances'], title: 'The village fire', text: 'Where the day’s makers gather in the evening for a sing-along.', controls: [dusk] },
    'calmshet-stage': { area: 'calmshet', pos: [20, 40, 5], programme: ['Opening night on 25 January', 'Acoustic sets', 'Sunset sets, and sunset evening views', 'Music performances all month'], title: 'The main stage', text: 'Opening night on 25 January, and the festival’s biggest performances all month.', controls: [showToggle('calmshet', 'Start the opening night', 'End the show'), { type: 'button', label: 'Make it night', actions: [{ set: 'timeOfDay', value: 0.95 }] }] },
    'calmshet-house': { area: 'calmshet', pos: [24, 31, 5], programme: ['10 resident painters working on the verandas', 'Conversations with the artists as they work'], title: 'The main house', text: 'The cream two-storey hill lodge, with wooden verandas and white railings wrapping every floor, on its stone terrace among the trees: home to the resident artists.', controls: [dusk] },
    'calmshet-runway': { area: 'calmshet', pos: [33, 31, 2], title: 'The fashion runway', text: 'A fashion segment inside the hub: collections, collectives and live runway shows.', controls: [showToggle('fashion', 'Start the runway show', 'End the show'), dusk] },
    'calmshet-archive': { area: 'calmshet', pos: [14, 31, 2], zoom: 1.6, programme: ['Paintings by the late K. N. Ramachandran', 'Artists from around India’s independence era', 'Antique prints and lithographs', 'The archive of the last two years'], title: 'The galleries and the archive', text: 'A gallery pavilion: the late K. N. Ramachandran’s paintings, the artists of the independence era, antique prints, and every event of the last two years to walk through.' },
    'calmshet-towers': { area: 'calmshet', pos: [28.5, 42, 9], title: 'Towers and drones', text: 'In Tech, Electronica & AI week, a drone swarm lights up the sky over Calmshet.', controls: [{ type: 'button', label: 'Launch the drones', primary: true, actions: [{ set: 'week', value: 2 }, { set: 'dronesOn', value: 1 }, { set: 'timeOfDay', value: 0.9 }] }] },
    'calmshet-pottery': { area: 'calmshet', pos: [34, 50, 3], zoom: 1.6, title: 'Pottery workshop', text: 'Hands in clay under the roof: a daily pottery workshop.', programme: ['Pottery workshop', 'Fire, glaze and take-home pieces'] },
    'calmshet-ai': { area: 'calmshet', pos: [28, 49, 3.5], zoom: 1.6, title: 'Comics corner and AI immersion', text: 'A dome for immersive, interactive AI installations, comics and short films.', programme: ['Comics corner: an interactive, immersive AI exhibit', 'Interactive installations and immersive experiences', 'Short films'] },
    'calmshet-sculpture': { area: 'calmshet', pos: [11.5, 46, 3.5], title: 'The sculptor’s lawn', text: 'A sculptor works on the grass through the month; visitors watch the piece take shape.', programme: ['A sculptor in residence', 'Sculpture and outdoor installations'] },
    'lefarm-tent2': { area: 'lefarm', pos: [68.5, 101.5, 4], title: 'Wine, cheese and fine dine', text: 'The second big top turns into a long-table dining room after dark.', programme: ['Wine and cheese sessions', 'Fine dine'], controls: [dusk] },
    'lefarm-yoga': { area: 'lefarm', pos: [50.5, 107, 2.5], title: 'The sunrise deck', text: 'A raised open deck facing the first light, above the lake.', programme: ['Morning yoga sessions', 'Meditation sessions', 'Healing sessions', 'Sunrise views'] },
    'lefarm-woodcut': { area: 'lefarm', pos: [57.5, 108.5, 2.5], zoom: 1.6, title: 'Woodcut workshop', text: 'Carve, inked and print: a woodcut workshop with the resident artists.', programme: ['Woodcut workshop'] },
    'lefarm-trail': { area: 'lefarm', pos: [57, 119, 2], title: 'Farm, trail and temple', text: 'The trails start at the farm stalls.', programme: ['Farm visits', 'Permaculture treks', 'Temple visits'] },
    'purrom-glass': { area: 'purrom', pos: [56, 15, 4], title: 'The Glass House', text: 'The dome with valley views is the morning room.', programme: ['Sunrise meditation', 'Yoga', 'Sound healing'], controls: [dusk] },
    'purrom-workshop': { area: 'purrom', pos: [40, 21.5, 3], zoom: 1.6, title: 'The workshop canopy', text: 'One hands-on workshop under the white canopy.', programme: ['One workshop'] },
    'purrom-acoustic': { area: 'purrom', pos: [56.5, 23, 3], title: 'The acoustic corner', text: 'A single acoustic act and music between films.', programme: ['One acoustic act', 'Music performances'] },
    'shambhala-cottage': { area: 'shambhala', pos: [26, 94, 3], title: 'The artists’ cottage', text: 'Three artists live and work here through the month.', programme: ['Painters', 'A rock-balancing artist', 'Acoustic musicians and singers'] },
    'shambhala-rocks': { area: 'shambhala', pos: [36, 95, 2], zoom: 1.6, title: 'Rock balancing', text: 'Stones stacked against gravity at the water’s edge.', programme: ['Rock balancing, with the artist on hand'] },
    'shambhala-workshop': { area: 'shambhala', pos: [47, 95, 2.5], title: 'The carpentry workshop', text: 'A hands-on workshop tent.', programme: ['Carpentry workshop', 'Tricks'] },
    'theeya-house': { area: 'theeya', pos: [113, 61, 4], title: 'The red house', text: 'The residents’ house, and a small theatre in the yard.', programme: ['About 4 resident artists', 'Theatre'], controls: [dusk] },
    'theeya-installations': { area: 'theeya', pos: [124, 66, 3], zoom: 1.6, title: 'The installations', text: 'About three installations are made here, on site, during the month.', programme: ['About 3 installations in progress', 'Resident artists at work'] },
    'company-ring': { area: 'company', pos: [77.5, 23, 3.5], title: 'The ring and the sunset circle', text: 'A ring installation on the lawn, facing the sunset. Meditation circles gather round it at dusk.', programme: ['2 installations in the grounds', 'Sunset meditation'], controls: [dusk] },
    'company-stage': { area: 'company', pos: [83.5, 11, 3], title: 'The open-air stage', text: 'The theatre’s stage beside the lawn.', programme: ['Theatre performances outdoors', 'The Company Theatre festival'], controls: [showToggle('company', 'Curtain up', 'Curtain down')] },
    'company-pavilion': { area: 'company', pos: [83, 22.5, 3], title: 'The workshop pavilion', text: 'Theatre workshops with the company.', programme: ['Theatre workshops'] },
    'company-studio': { area: 'company', pos: [66.5, 8.5, 3], zoom: 1.6, title: 'The artists’ studio', text: 'Six resident painters and sculptors work here; one wall carries the K. N. Ramachandran exhibit.', programme: ['6 resident artists: painters and sculptors', 'A K. N. Ramachandran exhibit'] },
    'company-interactive': { area: 'company', pos: [86.5, 18, 3], zoom: 1.6, title: 'The interactive installation', text: 'Touch it and it answers.', programme: ['1 interactive installation'], controls: [dusk] },
    'raiker-fire': { area: 'raiker', pos: [18, 76, 2], zoom: 2.2, title: 'The acoustic fire', text: 'Different acoustic artists play here, close and unplugged.', programme: ['Different acoustic artists'], controls: [dusk] },
    'raiker-gallery': { area: 'raiker', pos: [27, 68.3, 3], zoom: 1.6, title: 'The exhibition hall', text: 'Four exhibitions run through the month.', programme: ['Four exhibitions', 'Changing shows through the month'] },
    'raiker-interactive': { area: 'raiker', pos: [5, 62, 3], zoom: 1.6, title: 'The interactive installations', text: 'Multiple installations that react to you.', programme: ['Multiple interactive installations'], controls: [dusk] },
    'raiker-mega': { area: 'raiker', pos: [5.5, 57.4, 3], zoom: 1.6, title: 'The mega K. N. Ramachandran exhibition', text: 'The biggest room of the festival: a long hall of the late K. N. Ramachandran’s paintings, five easels wide.', programme: ['The mega K. N. Ramachandran exhibition', 'Guided walk-throughs on the weekends'] },
    'raiker-hall2': { area: 'raiker', pos: [3.2, 65.8, 3], zoom: 1.6, title: 'Exhibition two', text: 'A second hall on the farm’s west edge.', programme: ['One of the four exhibitions', 'Changing shows through the month'] },
    'raiker-hall3': { area: 'raiker', pos: [21.2, 69.2, 3], zoom: 1.6, title: 'Exhibition three', text: 'A third hall between the farmhouse and the fire.', programme: ['One of the four exhibitions', 'Changing shows through the month'] },
    'raiker-crystals': { area: 'raiker', pos: [28, 60.6, 3], zoom: 1.6, title: 'More installations', text: 'Two more interactive installations and a ring and a totem around the farm: touch them, photograph them, walk through.', programme: ['Multiple interactive installations', 'Multiple art installations'] },
    'calmshet-prints': { area: 'calmshet', pos: [11.8, 27.2, 3], zoom: 1.6, title: 'Antique prints and lithographs', text: 'A small hall of old prints and lithographs, with painters at work beside it.', programme: ['Antique prints and lithographs', 'Resident painters at their easels'] },
    'calmshet-sunset': { area: 'calmshet', pos: [36.4, 26.6, 2], zoom: 1.8, title: 'Sunset meditation', text: 'Mats laid out to face the sunset: sound healing and meditation as the light goes.', programme: ['Sunset meditation', 'Sound healing'], controls: [dusk] },
    'calmshet-film': { area: 'calmshet', pos: [12.4, 50.8, 3], zoom: 1.6, title: 'Short films', text: 'A small screen under the trees for short films.', programme: ['Short films'], controls: [dusk] },
    'lefarm-exhibits': { area: 'lefarm', pos: [65, 106.6, 3], zoom: 1.6, title: 'The exhibits', text: 'An antique exhibit, an AI-futurist show, the K. N. Ramachandran sketches and more, on easels under one roof.', programme: ['The antique exhibit', 'K. N. Ramachandran sketches', 'About 5 exhibits in all'] },
    'lefarm-beer': { area: 'lefarm', pos: [71.3, 116.6, 3], zoom: 1.6, title: 'The beer fest', text: 'A beer garden beside the stage, open all evening.', programme: ['Beer fest'], controls: [dusk] },
    'lefarm-shrine': { area: 'lefarm', pos: [50.1, 99.6, 3], zoom: 1.6, title: 'The temple trail', text: 'A small shrine on the trail: the walk to the temples and the permaculture farm starts here.', programme: ['Temple visits', 'Permaculture treks', 'Farm visits'] },
    'purrom-yoga': { area: 'purrom', pos: [57.6, 10.4, 2], zoom: 1.8, title: 'Sunrise circle', text: 'Yoga mats laid out under the Sahyadri sunrise: yoga, meditation and sound healing.', programme: ['Sunrise meditation', 'Yoga', 'Sound healing'] },
    'theeya-theatre': { area: 'theeya', pos: [109.4, 57.5, 3], zoom: 1.6, title: 'The village theatre', text: 'A small open stage beside the red house for theatre through the month.', programme: ['Theatre'], controls: [showToggle('theeya', 'Start the show', 'End the show')] },
    'theeya-yoga': { area: 'theeya', pos: [107.5, 76.9, 2], zoom: 1.8, title: 'Sunrise yoga and sound healing', text: 'Mats out by the pergola at first light.', programme: ['Sunrise meditation', 'Yoga', 'Sound healing'] },
    'company-sunset': { area: 'company', pos: [79.6, 19.7, 2], zoom: 1.8, title: 'Sunset meditation', text: 'Facing the sunset, on mats beside the lawn.', programme: ['Sunset meditation'], controls: [dusk] },
    'shambhala-exhibit': { area: 'shambhala', pos: [38.6, 80.8, 3], zoom: 1.6, title: 'The art exhibition', text: 'The one exhibition of the smallest venue: a single artist’s work on easels.', programme: ['One art exhibition'] },
    'checkin-arch': { area: 'checkin', pos: [90, 100, 4], title: 'Your festival journey', text: 'Park your car, walk in under the APPA arch, pick up a cycle or an e-bike, and get your APPA passport and itinerary. Slower travel, a cleaner festival.' },
    'square-fire': { area: 'checkin', pos: [88, 89, 1.5], title: 'The fire pit', text: 'The heart of the festival square: everyone ends up here at night, for songs, stories and the day’s gossip.', controls: [{ type: 'button', label: 'Make it night', actions: [{ set: 'timeOfDay', value: 0.92 }] }] },
    'square-stage': { area: 'checkin', pos: [96, 83, 3], title: 'The square stage', text: 'Open mics, local bands and surprise sets, right beside the fire and the food stalls.', controls: [showToggle('checkin', 'Start a set', 'End the set'), dusk] },
    'island-screen': { area: 'island', pos: [74.5, 56, 3], title: 'The Island Cinema', text: 'A screen on an island in the middle of the lake, benches under string lights, reached by boat. Films every evening.', controls: [showToggle('island', 'Start the film', 'End the film'), { type: 'button', label: 'Make it night', actions: [{ set: 'timeOfDay', value: 0.95 }] }] },
    'camp-tents': { area: 'camp', pos: [18, 114, 2], title: 'Stay & unwind', text: 'Tents, homestays and quiet zones. Stay for a night or for the whole month.', controls: [{ type: 'button', label: 'Night at the camp', actions: [{ set: 'timeOfDay', value: 0.92 }] }] },
    'hidden-act': { area: 'hidden', pos: [116, 111, 2.5], title: 'Tonight’s hidden act', text: 'Offbeat acts appear in fields, forests and villages. Follow the trail by cycle or on foot.', controls: [showToggle('hidden', 'Start the hidden act', 'End the act')] },
    lotus: { area: null, pos: [68, 38.5, 1.5], zoom: 0.55, title: 'The lotus on the lake', text: 'A floating installation at the heart of the festival. It lights up at dusk.', controls: [{ type: 'button', label: 'Light the lotus', primary: true, actions: [{ pulse: 'lotusGlow', dur: 16 }] }] }
  }
};
